name: Build and Save Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle' # Caches dependencies to make subsequent runs much faster

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Compile Project (APKs and AARs)
        run: |
          ./gradlew assembleDebug --stacktrace
          ./gradlew assembleRelease --stacktrace
          ./gradlew :Bcore:assembleDebug --stacktrace
          ./gradlew :Bcore:assembleRelease --stacktrace

      - name: Upload Application APKs
        uses: actions/upload-artifact@v4
        with:
          name: NewBlackbox-APKs
          path: app/build/outputs/apk/**/*.apk
          retention-days: 7

      - name: Upload Bcore AAR Frameworks
        uses: actions/upload-artifact@v4
        with:
          name: Bcore-AARs
          path: Bcore/build/outputs/aar/**/*.aar
          retention-days: 7
